my_memo_app/memo/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from forms import MemoForm
from models import Memo, db

# memoのBlueprint
memo_bp = Blueprint("memo", __name__, url_prefix="/memo")


# ==================================================
# ルーティング
# ==================================================
# 一覧
@memo_bp.route("/")
@login_required
def index():
    # メモ全件取得
    memos = Memo.query.filter_by(user_id=current_user.id).all()
    # 画面遷移
    return render_template("memo/index.html", memos=memos)


# 登録(Form使用)
@memo_bp.route("/create", methods=["GET", "POST"])
@login_required
def create():
    # Formインスタンス生成
    form = MemoForm()
    if form.validate_on_submit():
        # データ入力取得
        title = form.title.data
        content = form.content.data
        # 登録処理
        memo = Memo(
            title=title, content=content, user_id=current_user.id
        )  # <= 変更
        db.session.add(memo)
        db.session.commit()
        # フラッシュメッセージ
        flash("登録しました")
        # 画面遷移
        return redirect(url_for("memo.index"))
    # GET
    return render_template("memo/create_form.html", form=form)


# 更新(Form使用)
@memo_bp.route("/update/<int:memo_id>", methods=["GET", "POST"])
@login_required
def update(memo_id):
    # データベースからmemo_idに該当するレコードを探し, 見つからない場合は404エラーを表示
    target_data = Memo.query.filter_by(
        id=memo_id, user_id=current_user.id
    ).first_or_404()  # <= 変更
    # Formに入れ替え
    form = MemoForm(obj=target_data)
    # POST
    if request.method == "POST" and form.validate():
        # データ入力取得
        target_data.title = form.title.data
        target_data.content = form.content.data
        db.session.commit()
        # フラッシュメッセージ
        flash("変更しました")
        # 画面遷移
        return redirect(url_for("memo.index"))
    # GET
    return render_template(
        "memo/update_form.html", form=form, edit_id=target_data.id
    )


# 削除
@memo_bp.route("/delete/<int:memo_id>")
@login_required
def delete(memo_id):
    # データベースからmemo_idに該当するレコードを探し, 見つからない場合は404エラーを表示
    memo = Memo.query.filter_by(
        id=memo_id, user_id=current_user.id
    ).first_or_404()  # <= 変更
    # 削除処理
    db.session.delete(memo)
    db.session.commit()
    # フラッシュメッセージ
    flash("削除しました")
    # 画面遷移
    return redirect(url_for("memo.index"))


# wiki結果反映
@memo_bp.route("/create_from_search", methods=["POST"])
@login_required
def create_from_search():
    # 入力値の取得
    title = request.form["title"]
    content = request.form["content"]
    new_memo = Memo(title=title, content=content, user_id=current_user.id)
    # 追加処理
    db.session.add(new_memo)
    db.session.commit()
    # フラッシュメッセージ
    flash("wikiからデータ登録しました")
    # 画面遷移
    return redirect(url_for("memo.index"))

my_memo_app/wiki/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from forms import WikiForm
from wikipediaapi import Wikipedia

# Blueprint
wiki_bp = Blueprint("wiki", __name__, url_prefix="/wiki")

# 日本語版Wikipediaを利用
wiki_ja = Wikipedia("ja")


# ==================================================
# ルーティング
# ==================================================
@wiki_bp.route("/search", methods=["GET", "POST"])
@login_required
def search():
    # Form生成
    form = WikiForm()
    # POST
    if form.validate_on_submit():
        # データ入力取得
        keyword = form.keyword.data
        page = wiki_ja.page(keyword)
        disp_char = 400
        # 検索結果
        if page.exists():
            return render_template(
                "wiki/wiki_search_result.html",
                keyword=keyword,
                summary=page.summary[:disp_char],
                url=page.fullurl,
            )
        else:
            return render_template(
                "wiki/wiki_search_result.html",
                error="指定されたキーワードの結果は見つかりませんでした。",
            )

    # GET
    return render_template("wiki/wiki_search.html", form=form)

my_memo_app/templates/wiki/wiki_search.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h1 class="my-4">Wikipediaの検索</h1>
    {% from '_formhelpers.html' import render_field %}
    <form method="POST" action="{{url_for('wiki.search')}}" novalidate>
        {{form.hidden_tag()}}
        <div class="mb-3">
            {{form.keyword.label(class="form-label")}}
            {{form.keyword(class="form-control")}}
        </div>
        <div class="mb-3">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>

    <a href="{{url_for('memo.index')}}" class="btn btn-secondary mt-2">戻る</a>
</div>
{% endblock %}

my_memo_app/templates/wiki/wiki_search_result.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div class="mb-4">
        {% if error %}
            <h2>{{error}}</h2>
        {% else %}
            <h2>検索結果："{{keyword}}"</h2>
            <p>{{summary}}... <a href="{{url}}" target="_blank">Read more</a></p>
        {% endif %}
    </div>
    <!-- ▼▼▼ リスト 15-2の追加 ▼▼▼ -->
    <!-- メモに追加ボタン -->
    <form action="{{url_for('memo.create_from_search')}}" method="post" class="mb-3">
        <input type="hidden" name="title" value="{{keyword}}">
        <input type="hidden" name="content" value="{{summary}}">
        <input type="submit" value="メモに追加" class="btn btn-primary">
    </form>
    <!-- ▲▲▲ リスト 15-2の追加 ▲▲▲ -->
    <a href="{{url_for('memo.index')}}" class="btn btn-secondary">戻る</a>
</div>
{% endblock %}