my_memo_app/memo/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from forms import MemoForm
from models import Memo, db

# memoのBlueprint
memo_bp = Blueprint("memo", __name__, url_prefix="/memo")


# ==================================================
# ルーティング
# ==================================================
# 一覧
@memo_bp.route("/")
@login_required
def index():
    # メモ全件取得
    memos = Memo.query.filter_by(user_id=current_user.id).all()
    # 画面遷移
    return render_template("memo/index.html", memos=memos)


# 登録(Form使用)
@memo_bp.route("/create", methods=["GET", "POST"])
@login_required
def create():
    # Formインスタンス生成
    form = MemoForm()
    if form.validate_on_submit():
        # データ入力取得
        title = form.title.data
        content = form.content.data
        # 登録処理
        memo = Memo(
            title=title, content=content, user_id=current_user.id
        )  # <= 変更
        db.session.add(memo)
        db.session.commit()
        # フラッシュメッセージ
        flash("登録しました")
        # 画面遷移
        return redirect(url_for("memo.index"))
    # GET
    return render_template("memo/create_form.html", form=form)


# 更新(Form使用)
@memo_bp.route("/update/<int:memo_id>", methods=["GET", "POST"])
@login_required
def update(memo_id):
    # データベースからmemo_idに該当するレコードを探し, 見つからない場合は404エラーを表示
    target_data = Memo.query.filter_by(
        id=memo_id, user_id=current_user.id
    ).first_or_404()  # <= 変更
    # Formに入れ替え
    form = MemoForm(obj=target_data)
    # POST
    if request.method == "POST" and form.validate():
        # データ入力取得
        target_data.title = form.title.data
        target_data.content = form.content.data
        db.session.commit()
        # フラッシュメッセージ
        flash("変更しました")
        # 画面遷移
        return redirect(url_for("memo.index"))
    # GET
    return render_template(
        "memo/update_form.html", form=form, edit_id=target_data.id
    )


# 削除
@memo_bp.route("/delete/<int:memo_id>")
@login_required
def delete(memo_id):
    # データベースからmemo_idに該当するレコードを探し, 見つからない場合は404エラーを表示
    memo = Memo.query.filter_by(
        id=memo_id, user_id=current_user.id
    ).first_or_404()  # <= 変更
    # 削除処理
    db.session.delete(memo)
    db.session.commit()
    # フラッシュメッセージ
    flash("削除しました")
    # 画面遷移
    return redirect(url_for("memo.index"))


# wiki結果反映
@memo_bp.route("/create_from_search", methods=["POST"])
@login_required
def create_from_search():
    # 入力値の取得
    title = request.form["title"]
    content = request.form["content"]
    new_memo = Memo(title=title, content=content, user_id=current_user.id)
    # 追加処理
    db.session.add(new_memo)
    db.session.commit()
    # フラッシュメッセージ
    flash("wikiからデータ登録しました")
    # 画面遷移
    return redirect(url_for("memo.index"))

my_memo_app/templates/memo/create_form.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="my-4">新しいメモを作成</h1>
    {% from '_formhelpers.html' import render_field %}
    <form  method="POST" action="{{url_for('memo.create')}}" novalidate>
        {{form.hidden_tag()}}
        <div class="mb-3">
            {{render_field(form.title, class="form-control")}}
        </div>
        <div class="mb-3">
            {{render_field(form.content, class="form-control", rows=5)}}
        </div>
        <div class="mb-3">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>

    <a href="{{url_for('memo.index')}}" class="btn btn-secondary mt-2">戻る</a>
{% endblock %}

my_memo_app/templates/memo/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="my-4">メモ一覧</h1>
    {% if memos == [] %}
        <p>メモは登録されていません</p>
    {% else %}
        <ul class="list-group mb-4">
            {% for memo in memos %}
                <li class="list-group-item d-flex justify-content-between align-items-center">{{memo.title}}
                    <div>
                        <a href="{{url_for('memo.update', memo_id=memo.id)}}" class="btn btn-warning btn-sm">編集</a> |
                        <a href="{{url_for('memo.delete', memo_id=memo.id)}}" class="btn btn-danger btn-sm">削除</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- ▼▼▼▼▼ flashメッセージ ▼▼▼▼▼ -->
    {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            {{message}}
        </div>
    {% endfor %}
    <!-- ▲▲▲▲▲ flashメッセージ ▲▲▲▲▲ -->
    <a href="{{url_for('memo.create')}}" class="btn btn-primary">新しいメモを作成</a>
{% endblock %}

my_memo_app/templates/memo/update_form.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="my-4">メモを編集</h1>
    {% from '_formhelpers.html' import render_field %}
    <form method="POST" action="{{url_for('memo.update', memo_id=edit_id)}}" novalidate>
        {{form.hidden_tag()}}
        <div class="mb-3">
            {{render_field(form.title, class="form-control")}}
        </div>
        <div class="mb-3">
            {{render_field(form.content, class="form-control", rows=5)}}
        </div>
        <div class="mb-3">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>

    <a href="{{url_for('memo.index')}}" class="btn btn-secondary mt-2">戻る</a>
{% endblock %}